# Generated by Django 6.0.1 on 2026-01-24 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(
                        choices=[
                            ("topic_finder", "Topic Finder"),
                            ("researcher", "Researcher"),
                            ("script_writer", "Script Writer"),
                            ("scene_planner", "Scene Planner"),
                            ("image_prompter", "Image Prompter"),
                            ("scene_generator", "Scene Generator"),
                            ("video_generator", "Video Generator"),
                            ("video_composer", "Video Composer"),
                            ("thumbnail_generator", "Thumbnail Generator"),
                        ],
                        max_length=50,
                        verbose_name="에이전트",
                    ),
                ),
                (
                    "prompt_content",
                    models.TextField(
                        help_text="Markdown 형식", verbose_name="프롬프트 내용"
                    ),
                ),
                ("version", models.IntegerField(default=1, verbose_name="버전")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_prompts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="수정자",
                    ),
                ),
            ],
            options={
                "verbose_name": "에이전트 프롬프트",
                "verbose_name_plural": "에이전트 프롬프트",
                "ordering": ["agent_name", "-version"],
            },
        ),
        migrations.CreateModel(
            name="AgentPromptHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_content", models.TextField(verbose_name="이전 내용")),
                ("previous_version", models.IntegerField(verbose_name="이전 버전")),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("change_note", models.TextField(blank=True, verbose_name="변경 메모")),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompt_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="변경자",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="prompts.agentprompt",
                    ),
                ),
            ],
            options={
                "verbose_name": "프롬프트 변경 이력",
                "verbose_name_plural": "프롬프트 변경 이력",
                "ordering": ["-changed_at"],
            },
        ),
    ]
