# Generated by Django 6.0.1 on 2026-01-26 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgentPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(choices=[('topic_finder', 'Topic Finder'), ('researcher', 'Researcher'), ('script_writer', 'Script Writer'), ('scene_planner', 'Scene Planner'), ('image_prompter', 'Image Prompter'), ('scene_generator', 'Scene Generator'), ('video_generator', 'Video Generator'), ('video_composer', 'Video Composer'), ('thumbnail_generator', 'Thumbnail Generator')], max_length=50, verbose_name='에이전트')),
                ('prompt_content', models.TextField(help_text='Markdown 형식', verbose_name='프롬프트 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_prompts', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자별 프롬프트',
                'verbose_name_plural': '사용자별 프롬프트',
                'unique_together': {('user', 'agent_name')},
            },
        ),
    ]
