# Generated by Django 6.0.1 on 2026-01-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apikey",
            options={
                "ordering": ["service", "-is_default", "name"],
                "verbose_name": "API 키",
                "verbose_name_plural": "API 키",
            },
        ),
        migrations.AlterUniqueTogether(
            name="apikey",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="apikey",
            name="is_default",
            field=models.BooleanField(default=True, verbose_name="기본 키"),
        ),
        migrations.AddField(
            model_name="apikey",
            name="name",
            field=models.CharField(
                default="기본",
                help_text="구분용 이름 (예: 개인용, 회사용)",
                max_length=100,
                verbose_name="키 이름",
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="service",
            field=models.CharField(
                choices=[("gemini", "Google Gemini"), ("replicate", "Replicate")],
                max_length=50,
                verbose_name="서비스",
            ),
        ),
    ]
