# Generated by Django 6.0.1 on 2026-01-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_apikey_options_alter_apikey_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gemini_model",
            field=models.CharField(
                choices=[
                    ("flash", "Gemini 2.0 Flash (빠름, 저렴)"),
                    ("pro", "Gemini 2.5 Pro (고품질)"),
                ],
                default="flash",
                help_text="리서치/대본 작성에 사용할 모델",
                max_length=20,
                verbose_name="Gemini 모델",
            ),
        ),
    ]
