# Generated by Django 6.0.1 on 2026-01-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_gemini_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gemini_model',
            field=models.CharField(choices=[('flash', 'Gemini 3 Flash (빠름, 저렴)'), ('pro', 'Gemini 3 Pro (고품질)')], default='flash', help_text='리서치/대본 작성에 사용할 모델', max_length=20, verbose_name='Gemini 모델'),
        ),
    ]
