# Generated by Django 6.0.1 on 2026-01-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_gemini_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gemini_model',
            field=models.CharField(choices=[('2.5-flash', 'Gemini 2.5 Flash (최신, 저렴)'), ('2.5-pro', 'Gemini 2.5 Pro (최신, 고품질)'), ('flash', 'Gemini 3 Flash (빠름)'), ('pro', 'Gemini 3 Pro (고품질)')], default='flash', help_text='리서치/대본 작성에 사용할 모델', max_length=20, verbose_name='Gemini 모델'),
        ),
    ]
