# Generated by Django 6.0.1 on 2026-02-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_gemini_25_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='service',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('replicate', 'Replicate'), ('freepik', 'Freepik')], max_length=50, verbose_name='서비스'),
        ),
    ]
