# Generated by Django 6.0.1 on 2026-02-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_apikey_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='service',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('replicate', 'Replicate'), ('freepik', 'Freepik'), ('freepik_cookie', 'Freepik 쿠키'), ('freepik_wallet', 'Freepik Wallet ID')], max_length=50, verbose_name='서비스'),
        ),
    ]
