# Generated by Django 6.0.1 on 2026-02-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_freepikaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='freepikaccount',
            name='cookie_expired',
            field=models.BooleanField(default=False, verbose_name='쿠키 만료'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='service',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('replicate', 'Replicate'), ('freepik', 'Freepik'), ('freepik_cookie', 'Freepik 쿠키'), ('freepik_wallet', 'Freepik Wallet ID'), ('freepik_email', 'Freepik 이메일'), ('freepik_password', 'Freepik 비밀번호')], max_length=50, verbose_name='서비스'),
        ),
    ]
