# Generated by Django 6.0.1 on 2026-02-10 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_cookie_expired_to_freepikaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freepikaccount',
            name='first_download_at',
        ),
    ]
