# Generated by Django 6.0.1 on 2026-02-10 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_first_download_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freepikaccount',
            name='is_exhausted',
        ),
    ]
