# Generated by Django 6.0.1 on 2026-01-24 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("topic_finder", "주제 찾기"),
                            ("researcher", "리서치"),
                            ("script_writer", "대본 작성"),
                            ("scene_planner", "씬 분할"),
                            ("image_prompter", "이미지 프롬프트"),
                            ("scene_generator", "이미지 생성"),
                            ("video_generator", "동영상 생성"),
                            ("video_composer", "영상 편집"),
                            ("thumbnail_generator", "썸네일 생성"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="단계명",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=100, verbose_name="표시명"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("order", models.IntegerField(default=0, verbose_name="순서")),
                (
                    "can_run_independently",
                    models.BooleanField(default=False, verbose_name="독립 실행 가능"),
                ),
                (
                    "manual_input_description",
                    models.TextField(blank=True, verbose_name="수동 입력 설명"),
                ),
            ],
            options={
                "verbose_name": "파이프라인 단계",
                "verbose_name_plural": "파이프라인 단계",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="프로젝트명")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "초안"),
                            ("in_progress", "진행 중"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "final_video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="projects/videos/",
                        verbose_name="최종 영상",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="projects/thumbnails/",
                        verbose_name="썸네일",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "프로젝트",
                "verbose_name_plural": "프로젝트",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Draft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="제목")),
                ("content", models.TextField(verbose_name="대본 내용")),
                ("char_count", models.IntegerField(default=0, verbose_name="글자수")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft",
                        to="pipeline.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "대본",
                "verbose_name_plural": "대본",
            },
        ),
        migrations.CreateModel(
            name="CharacterSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="projects/characters/", verbose_name="캐릭터 시트"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="캐릭터 설명"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_sheet",
                        to="pipeline.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "캐릭터 시트",
                "verbose_name_plural": "캐릭터 시트",
            },
        ),
        migrations.CreateModel(
            name="Research",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_url", models.URLField(blank=True, verbose_name="원본 URL")),
                (
                    "topic",
                    models.CharField(blank=True, max_length=500, verbose_name="주제"),
                ),
                ("transcript", models.TextField(blank=True, verbose_name="자막 원본")),
                ("summary", models.TextField(blank=True, verbose_name="요약")),
                (
                    "key_points",
                    models.JSONField(default=list, verbose_name="핵심 포인트"),
                ),
                (
                    "statistics",
                    models.JSONField(default=list, verbose_name="통계/수치"),
                ),
                ("quotes", models.JSONField(default=list, verbose_name="인용구")),
                (
                    "additional_info",
                    models.TextField(blank=True, verbose_name="추가 정보"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research",
                        to="pipeline.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "리서치",
                "verbose_name_plural": "리서치",
            },
        ),
        migrations.CreateModel(
            name="StepExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("running", "실행 중"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                            ("cancelled", "취소"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "progress_percent",
                    models.IntegerField(default=0, verbose_name="진행률"),
                ),
                (
                    "progress_message",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="진행 메시지"
                    ),
                ),
                (
                    "manual_input",
                    models.TextField(blank=True, default="", verbose_name="수동 입력"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="에러 메시지"),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_executions",
                        to="pipeline.project",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pipeline.pipelinestep",
                        verbose_name="단계",
                    ),
                ),
            ],
            options={
                "verbose_name": "단계 실행",
                "verbose_name_plural": "단계 실행",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_id", models.CharField(max_length=50, verbose_name="영상 ID")),
                ("title", models.CharField(max_length=500, verbose_name="제목")),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "channel",
                    models.CharField(blank=True, max_length=200, verbose_name="채널"),
                ),
                (
                    "view_count",
                    models.BigIntegerField(default=0, verbose_name="조회수"),
                ),
                (
                    "viral_ratio",
                    models.FloatField(default=0, verbose_name="바이럴 비율"),
                ),
                ("reason", models.TextField(blank=True, verbose_name="선정 이유")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic",
                        to="pipeline.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "주제",
                "verbose_name_plural": "주제",
            },
        ),
        migrations.CreateModel(
            name="Scene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scene_number", models.IntegerField(verbose_name="씬 번호")),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("intro", "인트로"),
                            ("body_1", "본문 1"),
                            ("body_2", "본문 2"),
                            ("body_3", "본문 3"),
                            ("action", "액션"),
                            ("outro", "아웃트로"),
                        ],
                        default="body_1",
                        max_length=20,
                        verbose_name="섹션",
                    ),
                ),
                ("narration", models.TextField(verbose_name="나레이션 (자막용)")),
                (
                    "narration_tts",
                    models.TextField(blank=True, verbose_name="나레이션 (TTS용)"),
                ),
                ("duration", models.FloatField(default=0, verbose_name="길이(초)")),
                (
                    "has_character",
                    models.BooleanField(default=False, verbose_name="캐릭터 등장"),
                ),
                (
                    "image_prompt",
                    models.TextField(blank=True, verbose_name="이미지 프롬프트"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="projects/scenes/images/",
                        verbose_name="이미지",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="projects/scenes/videos/",
                        verbose_name="영상",
                    ),
                ),
                (
                    "audio",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="projects/scenes/audio/",
                        verbose_name="음성",
                    ),
                ),
                (
                    "subtitle_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="projects/scenes/subtitles/",
                        verbose_name="자막",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenes",
                        to="pipeline.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "씬",
                "verbose_name_plural": "씬",
                "ordering": ["scene_number"],
                "unique_together": {("project", "scene_number")},
            },
        ),
    ]
