# Generated by Django 6.0.1 on 2026-01-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="research",
            name="additional_info",
        ),
        migrations.RemoveField(
            model_name="research",
            name="key_points",
        ),
        migrations.RemoveField(
            model_name="research",
            name="statistics",
        ),
        migrations.AddField(
            model_name="research",
            name="best_title",
            field=models.JSONField(default=dict, verbose_name="선정 제목"),
        ),
        migrations.AddField(
            model_name="research",
            name="narrative_structure",
            field=models.JSONField(default=dict, verbose_name="서사 구조"),
        ),
        migrations.AddField(
            model_name="research",
            name="numbers",
            field=models.JSONField(default=list, verbose_name="숫자/통계"),
        ),
        migrations.AddField(
            model_name="research",
            name="paradox",
            field=models.JSONField(default=dict, verbose_name="역설 요소"),
        ),
        migrations.AddField(
            model_name="research",
            name="person_stories",
            field=models.JSONField(default=list, verbose_name="인물 사례"),
        ),
        migrations.AddField(
            model_name="research",
            name="sources",
            field=models.JSONField(default=list, verbose_name="출처"),
        ),
        migrations.AddField(
            model_name="research",
            name="time_change",
            field=models.JSONField(default=dict, verbose_name="시간 변화"),
        ),
        migrations.AddField(
            model_name="research",
            name="title_candidates",
            field=models.JSONField(default=list, verbose_name="제목 후보"),
        ),
        migrations.AddField(
            model_name="research",
            name="viewer_connection",
            field=models.JSONField(default=dict, verbose_name="시청자 연결"),
        ),
    ]
