# Generated by Django 6.0.1 on 2026-01-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0002_remove_research_additional_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stepexecution",
            name="logs",
            field=models.JSONField(default=list, verbose_name="실행 로그"),
        ),
    ]
