# Generated by Django 6.0.1 on 2026-01-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0003_stepexecution_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="stepexecution",
            name="model_type",
            field=models.CharField(
                choices=[("flash", "Gemini 3 Flash"), ("pro", "Gemini 3 Pro")],
                default="flash",
                max_length=20,
                verbose_name="모델",
            ),
        ),
    ]
