# Generated by Django 6.0.1 on 2026-01-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0004_stepexecution_model_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="stepexecution",
            name="intermediate_data",
            field=models.JSONField(default=dict, verbose_name="중간 데이터"),
        ),
    ]
