# Generated by Django 6.0.1 on 2026-01-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0005_stepexecution_intermediate_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="stepexecution",
            name="estimated_cost",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                max_digits=10,
                verbose_name="예상 비용(USD)",
            ),
        ),
        migrations.AddField(
            model_name="stepexecution",
            name="input_tokens",
            field=models.IntegerField(default=0, verbose_name="입력 토큰"),
        ),
        migrations.AddField(
            model_name="stepexecution",
            name="output_tokens",
            field=models.IntegerField(default=0, verbose_name="출력 토큰"),
        ),
        migrations.AddField(
            model_name="stepexecution",
            name="total_tokens",
            field=models.IntegerField(default=0, verbose_name="총 토큰"),
        ),
    ]
