# Generated by Django 6.0.1 on 2026-01-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0006_stepexecution_token_usage"),
    ]

    operations = [
        migrations.AddField(
            model_name="research",
            name="article_summaries",
            field=models.JSONField(default=list, verbose_name="기사별 요약"),
        ),
    ]
