# Generated by Django 6.0.1 on 2026-01-24 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0007_add_article_summaries"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectImageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "style_description",
                    models.TextField(
                        blank=True,
                        help_text="예: photorealistic, vibrant colors, news documentary style",
                        verbose_name="스타일 설명",
                    ),
                ),
                (
                    "character_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="projects/characters/",
                        verbose_name="캐릭터 이미지",
                    ),
                ),
                (
                    "character_description",
                    models.TextField(
                        blank=True,
                        help_text="예: simple webtoon style mascot, curly black hair, round glasses, blue shirt",
                        verbose_name="캐릭터 설명",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_settings",
                        to="pipeline.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "이미지 설정",
                "verbose_name_plural": "이미지 설정",
            },
        ),
        migrations.CreateModel(
            name="SampleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="projects/samples/", verbose_name="샘플 이미지"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="설명"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="순서")),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sample_images",
                        to="pipeline.projectimagesettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "샘플 이미지",
                "verbose_name_plural": "샘플 이미지",
                "ordering": ["order"],
            },
        ),
    ]
