# Generated by Django 6.0.1 on 2026-01-24 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0008_projectimagesettings_sampleimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "image",
                    models.ImageField(
                        upload_to="presets/characters/", verbose_name="캐릭터 이미지"
                    ),
                ),
                (
                    "character_prompt",
                    models.TextField(
                        help_text="예: simple webtoon style mascot, curly black hair, round glasses, blue shirt",
                        verbose_name="캐릭터 프롬프트",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="기본값"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "캐릭터",
                "verbose_name_plural": "캐릭터",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="ImageStylePreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "style_prompt",
                    models.TextField(
                        help_text="예: photorealistic, vibrant colors, news documentary style, professional lighting",
                        verbose_name="스타일 프롬프트",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="기본값"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "이미지 스타일",
                "verbose_name_plural": "이미지 스타일",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="VoicePreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "reference_audio",
                    models.FileField(
                        upload_to="presets/voices/", verbose_name="참조 음성 (WAV)"
                    ),
                ),
                (
                    "reference_text",
                    models.TextField(
                        help_text="참조 음성에서 말하는 내용",
                        verbose_name="참조 음성 텍스트",
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(default=0.7, verbose_name="Temperature"),
                ),
                ("top_p", models.FloatField(default=0.7, verbose_name="Top P")),
                (
                    "repetition_penalty",
                    models.FloatField(default=1.2, verbose_name="Repetition Penalty"),
                ),
                ("seed", models.IntegerField(default=42, verbose_name="Seed")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="기본값"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "TTS 음성",
                "verbose_name_plural": "TTS 음성",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.RemoveField(
            model_name="projectimagesettings",
            name="project",
        ),
        migrations.RemoveField(
            model_name="sampleimage",
            name="settings",
        ),
        migrations.AddField(
            model_name="project",
            name="character",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pipeline.characterpreset",
                verbose_name="캐릭터",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="image_style",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pipeline.imagestylepreset",
                verbose_name="이미지 스타일",
            ),
        ),
        migrations.CreateModel(
            name="StyleSampleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="presets/styles/", verbose_name="샘플 이미지"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="설명"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="순서")),
                (
                    "style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sample_images",
                        to="pipeline.imagestylepreset",
                    ),
                ),
            ],
            options={
                "verbose_name": "스타일 샘플 이미지",
                "verbose_name_plural": "스타일 샘플 이미지",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="voice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pipeline.voicepreset",
                verbose_name="TTS 음성",
            ),
        ),
        migrations.DeleteModel(
            name="CharacterSheet",
        ),
        migrations.DeleteModel(
            name="ProjectImageSettings",
        ),
        migrations.DeleteModel(
            name="SampleImage",
        ),
    ]
