# Generated by Django 6.0.1 on 2026-01-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0011_add_tts_generator_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="scene",
            name="narration_word_count",
            field=models.IntegerField(default=0, verbose_name="원본 단어 수"),
        ),
        migrations.AddField(
            model_name="scene",
            name="subtitle_status",
            field=models.CharField(
                choices=[
                    ("none", "없음"),
                    ("matched", "매칭됨"),
                    ("mismatch", "불일치"),
                ],
                default="none",
                max_length=20,
                verbose_name="자막 상태",
            ),
        ),
        migrations.AddField(
            model_name="scene",
            name="subtitle_word_count",
            field=models.IntegerField(default=0, verbose_name="SRT 단어 수"),
        ),
        migrations.AlterField(
            model_name="pipelinestep",
            name="name",
            field=models.CharField(
                choices=[
                    ("topic_finder", "주제 찾기"),
                    ("researcher", "리서치"),
                    ("script_writer", "대본 작성"),
                    ("scene_planner", "씬 분할"),
                    ("image_prompter", "이미지 프롬프트"),
                    ("scene_generator", "이미지 생성"),
                    ("tts_generator", "TTS 생성"),
                    ("video_generator", "동영상 생성"),
                    ("video_composer", "영상 편집"),
                    ("thumbnail_generator", "썸네일 생성"),
                ],
                max_length=50,
                unique=True,
                verbose_name="단계명",
            ),
        ),
    ]
