# Generated by Django 6.0.1 on 2026-01-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0012_add_subtitle_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="full_subtitles",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="projects/subtitles/",
                verbose_name="전체 자막",
            ),
        ),
    ]
