# Generated by Django 6.0.1 on 2026-01-25 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0013_add_full_subtitles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ThumbnailStylePreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "style_type",
                    models.CharField(
                        choices=[
                            ("youtube", "YouTube (눈에 띄는)"),
                            ("minimalist", "미니멀 (깔끔한)"),
                            ("bold", "볼드 (강렬한)"),
                        ],
                        default="youtube",
                        max_length=20,
                        verbose_name="스타일 타입",
                    ),
                ),
                (
                    "example_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="presets/thumbnails/",
                        verbose_name="예시 이미지",
                    ),
                ),
                (
                    "prompt_template",
                    models.TextField(
                        default="YouTube thumbnail for Korean economy video.\n\nMain visual: {main_keyword} related scene\nKorean text: '{title}' (large, bold, contrasting color)\nStyle: {style_type}, dramatic lighting\nEmotion: curiosity, urgency\n\nTechnical requirements:\n- 16:9 aspect ratio (1280x720)\n- High contrast for mobile visibility\n- Clean composition with focal point\n- Professional financial theme",
                        help_text="사용 가능한 변수: {title}, {hook}, {main_keyword}",
                        verbose_name="프롬프트 템플릿",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="기본값"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thumbnail_styles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "썸네일 스타일",
                "verbose_name_plural": "썸네일 스타일",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="thumbnail_style",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pipeline.thumbnailstylepreset",
                verbose_name="썸네일 스타일",
            ),
        ),
        migrations.CreateModel(
            name="UploadInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="70자 이내 권장", max_length=100, verbose_name="제목"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("tags", models.JSONField(default=list, verbose_name="태그")),
                (
                    "timeline",
                    models.JSONField(
                        default=list,
                        help_text='[{"time": "0:00", "title": "인트로"}, ...]',
                        verbose_name="타임라인",
                    ),
                ),
                (
                    "thumbnail_prompt",
                    models.TextField(blank=True, verbose_name="썸네일 프롬프트"),
                ),
                (
                    "category_id",
                    models.CharField(
                        default="25", max_length=10, verbose_name="카테고리 ID"
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        default="News & Politics",
                        max_length=50,
                        verbose_name="카테고리명",
                    ),
                ),
                (
                    "privacy_status",
                    models.CharField(
                        default="private", max_length=20, verbose_name="공개 상태"
                    ),
                ),
                (
                    "made_for_kids",
                    models.BooleanField(default=False, verbose_name="아동용"),
                ),
                (
                    "contains_synthetic_media",
                    models.BooleanField(default=True, verbose_name="AI 생성 콘텐츠"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_info",
                        to="pipeline.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "업로드 정보",
                "verbose_name_plural": "업로드 정보",
            },
        ),
    ]
