# Generated by Django 6.0.1 on 2026-01-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0014_add_thumbnail_style_and_upload_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="scene",
            name="audio_duration",
            field=models.FloatField(default=0, verbose_name="실제 오디오 길이(초)"),
        ),
    ]
