# Generated by Django 6.0.1 on 2026-01-26 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0016_add_image_model_to_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTSJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '대기'), ('processing', '처리 중'), ('completed', '완료'), ('cancelled', '취소'), ('failed', '실패')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tts_jobs', to='pipeline.project')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tts_jobs', to='pipeline.scene')),
            ],
            options={
                'verbose_name': 'TTS 작업',
                'verbose_name_plural': 'TTS 작업',
                'ordering': ['created_at', 'scene__scene_number'],
            },
        ),
    ]
