# Generated by Django 6.0.1 on 2026-01-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0017_ttsjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='manual_notes',
            field=models.TextField(blank=True, help_text='직접 입력한 참고 자료. 대본 작성 시 활용됨.', verbose_name='수동 추가 자료'),
        ),
    ]
