# Generated by Django 6.0.1 on 2026-01-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0018_research_manual_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepexecution',
            name='acknowledged',
            field=models.BooleanField(default=False, verbose_name='확인됨'),
        ),
    ]
