# Generated by Django 6.0.1 on 2026-01-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0019_add_acknowledged_to_execution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepexecution',
            name='model_type',
            field=models.CharField(choices=[('2.5-flash', 'Gemini 2.5 Flash'), ('2.5-pro', 'Gemini 2.5 Pro'), ('flash', 'Gemini 3 Flash'), ('pro', 'Gemini 3 Pro')], default='2.5-flash', max_length=20, verbose_name='모델'),
        ),
    ]
