# Generated by Django 6.0.1 on 2026-01-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0020_update_model_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_model',
            field=models.CharField(choices=[('gemini-3-pro', 'Gemini 3 Pro ($0.134/장, 한글 잘됨)'), ('gemini-2.5-flash', 'Gemini 2.5 Flash ($0.039/장, 한글 △)'), ('flux-schnell', 'FLUX.1-schnell ($0.003/장, 빠름)'), ('sdxl', 'SDXL ($0.005/장)')], default='gemini-3-pro', max_length=30, verbose_name='이미지 생성 모델'),
        ),
    ]
