# Generated by Django 6.0.1 on 2026-02-04 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0022_update_image_model_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='content_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='summary, key_topics, viewer_interests, highlight_comments, draft_outline, research_keywords 등', verbose_name='콘텐츠 분석'),
        ),
        migrations.AddField(
            model_name='research',
            name='target_keywords',
            field=models.JSONField(blank=True, default=list, verbose_name='리서치 키워드'),
        ),
        migrations.AddField(
            model_name='research',
            name='transcript_is_auto',
            field=models.BooleanField(default=False, verbose_name='자동생성 자막 여부'),
        ),
        migrations.AddField(
            model_name='research',
            name='transcript_language',
            field=models.CharField(blank=True, max_length=10, verbose_name='자막 언어'),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='name',
            field=models.CharField(choices=[('topic_finder', '주제 찾기'), ('youtube_collector', 'YouTube 수집'), ('content_analyzer', '콘텐츠 분석'), ('researcher', '리서치'), ('script_writer', '대본 작성'), ('scene_planner', '씬 분할'), ('image_prompter', '이미지 프롬프트'), ('scene_generator', '이미지 생성'), ('tts_generator', 'TTS 생성'), ('video_generator', '동영상 생성'), ('video_composer', '영상 편집'), ('thumbnail_generator', '썸네일 생성')], max_length=50, unique=True, verbose_name='단계명'),
        ),
        migrations.CreateModel(
            name='YouTubeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=50, verbose_name='댓글 ID')),
                ('author', models.CharField(max_length=100, verbose_name='작성자')),
                ('text', models.TextField(verbose_name='댓글 내용')),
                ('like_count', models.IntegerField(default=0, verbose_name='좋아요 수')),
                ('reply_count', models.IntegerField(default=0, verbose_name='답글 수')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='작성일')),
                ('is_highlighted', models.BooleanField(default=False, verbose_name='주요 댓글')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_comments', to='pipeline.research')),
            ],
            options={
                'verbose_name': 'YouTube 댓글',
                'verbose_name_plural': 'YouTube 댓글',
                'ordering': ['-like_count'],
            },
        ),
    ]
