# Generated by Django 6.0.1 on 2026-02-04 14:19

from django.db import migrations


def add_tts_converter_step(apps, schema_editor):
    PipelineStep = apps.get_model('pipeline', 'PipelineStep')
    if not PipelineStep.objects.filter(name='tts_converter').exists():
        PipelineStep.objects.create(
            name='tts_converter',
            display_name='TTS 변환',
            order=62,
        )


def remove_tts_converter_step(apps, schema_editor):
    PipelineStep = apps.get_model('pipeline', 'PipelineStep')
    PipelineStep.objects.filter(name='tts_converter').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0023_add_youtube_features'),
    ]

    operations = [
        migrations.RunPython(add_tts_converter_step, remove_tts_converter_step),
    ]
