# Generated by Django 6.0.1 on 2026-02-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0024_add_tts_converter_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterpreset',
            name='character_prompt',
            field=models.TextField(blank=True, help_text='선택사항. 없으면 캐릭터 이미지만 참조', verbose_name='캐릭터 프롬프트'),
        ),
        migrations.AlterField(
            model_name='imagestylepreset',
            name='style_prompt',
            field=models.TextField(blank=True, help_text='선택사항. 없으면 샘플 이미지만 참조', verbose_name='스타일 프롬프트'),
        ),
    ]
