# Generated by Django 6.0.1 on 2026-02-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0026_add_upload_info_generator_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='freepik_interval',
            field=models.IntegerField(default=0, help_text='N번째 씬마다 스톡 영상 삽입 (0=사용 안함)', verbose_name='스톡 영상 간격'),
        ),
        migrations.AddField(
            model_name='scene',
            name='stock_video',
            field=models.FileField(blank=True, null=True, upload_to='projects/scenes/stock_videos/', verbose_name='스톡 영상'),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='name',
            field=models.CharField(choices=[('topic_finder', '주제 찾기'), ('youtube_collector', 'YouTube 수집'), ('content_analyzer', '콘텐츠 분석'), ('researcher', '리서치'), ('script_writer', '대본 작성'), ('scene_planner', '씬 분할'), ('image_prompter', '이미지 프롬프트'), ('scene_generator', '이미지 생성'), ('tts_generator', 'TTS 생성'), ('video_generator', '동영상 생성'), ('video_composer', '영상 편집'), ('thumbnail_generator', '썸네일 생성'), ('upload_info_generator', '업로드 정보 생성'), ('freepik_video', '스톡 영상')], max_length=50, unique=True, verbose_name='단계명'),
        ),
    ]
