# Generated by Django 6.0.1 on 2026-02-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0028_add_freepik_video_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='stock_video_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='스톡 영상 ID'),
        ),
    ]
