# Generated by Django 6.0.1 on 2026-02-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0029_scene_stock_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnailstylepreset',
            name='prompt_template',
            field=models.TextField(default="YouTube thumbnail for a video.\n\nMain visual: {main_keyword} related scene\nKorean text: '{title}' (large, bold, contrasting color)\nStyle: {style_type}, dramatic lighting\nEmotion: curiosity, urgency\n\nTechnical requirements:\n- 16:9 aspect ratio (1280x720)\n- High contrast for mobile visibility\n- Clean composition with focal point", help_text='사용 가능한 변수: {title}, {hook}, {main_keyword}', verbose_name='프롬프트 템플릿'),
        ),
    ]
