# Generated by Django 6.0.1 on 2026-02-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0030_update_thumbnail_prompt_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadinfo',
            name='references',
            field=models.TextField(blank=True, verbose_name='참고자료'),
        ),
        migrations.AlterField(
            model_name='project',
            name='freepik_interval',
            field=models.IntegerField(default=2, help_text='N번째 씬마다 스톡 영상 삽입 (0=사용 안함)', verbose_name='스톡 영상 간격'),
        ),
    ]
