# Generated by Django 6.0.1 on 2026-04-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0031_add_references_to_uploadinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='visual_type',
            field=models.CharField(choices=[('slide', '슬라이드'), ('image', 'AI 이미지'), ('stock_video', '스톡 영상')], default='image', max_length=20, verbose_name='비주얼 타입'),
        ),
    ]
